### ISSUE TITLE
Calling parent constructor with instructions from ReadMe throws error

### ISSUE THREAD

**Issue by maximilianschmitt** [bevry/csextends#1]
Using `this.__super__.constructor.apply(this, arguments)` to call the parent constructor within the child constructor will throw an error telling you that this.**super** is not defined.

To call the parent constructor correctly, do this:

```
var MyJavaScriptClass = SomeCoffeeScriptClass.extend({
    constructor: function(){
        MyJavaScriptClass.__super__.constructor.apply(this, arguments);
    }
});
```

**Comment by balupton** [comment]
see #4
