### ISSUE TITLE
Make coffee-script a devDependency

### ISSUE THREAD

**Issue by thompsnm** [bevry/csextends#5]
Could you please make coffee-script a `devDependency` rather than a regular `dependency`? I only today discovered that coffee-script was being pulled into my project when my builds started failing due to [this issue](https://github.com/jashkenas/coffeescript/issues/4805). I personally have no need of coffee-script and would prefer that it isn't pulled in. Unfortunately, the csextends module is itself a transitive dependency five layers deep in my dependency tree, so I have no option to remove it from my code base.

**Comment by balupton** [comment]
good point, will do the change now

**Comment by balupton** [comment]
released to v1.2.0 sorry it took so long

**Comment by thompsnm** [comment]
No worries, thank you!
